### ISSUE TITLE
Ingestion engine | Improved offers tracking

### ISSUE THREAD

**Issue by orbitlens** [orbitlens/stellar-expert-explorer#99]
- [x] Generate offer created/deleted effects.
- [x] Add offer id and corresponding index for trade effects (required by #90) .
- [ ] ~Enable "time travel" feature for account offers list (show active offers for any particular date).~
- [x] Aggregate offer stats in separate collection (required by #92). Not sure about that, maybe a runtime aggregation of all effects related to the specific offer may provide sufficient performance. Need to test it in the worst-case censorious.
